services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: slm_user
      POSTGRES_PASSWORD: 9KjG1MuYCoYwEhHjLPzvElSx
      POSTGRES_DB: slm_db
    ports:
      - '5432:5432'
    volumes:
      - slm_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U slm_user -d slm_db']
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://slm_user:9KjG1MuYCoYwEhHjLPzvElSx@postgres:5432/slm_db?schema=public
      JWT_SECRET: 33b5bd0a18b5edbaa211c467141b2c38b68aa56b296999ce116b25798bfdfb8b
      JWT_EXPIRES_IN: 15m
      REFRESH_TOKEN_EXPIRES_IN: 7d
      PORT: 4000
      NODE_ENV: production
      CLIENT_URL: https://s-lab.uz
      UPLOAD_DIR: uploads
      MAX_FILE_SIZE_MB: 10
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '4000:4000'
      - '5555:5555'
    volumes:
      - slm_uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - '5173:80'

volumes:
  slm_postgres_data:
  slm_uploads: