-- Data migration: seed real "Xizmatlar" (Service) + "Narxlar" (Price)
-- rows for 7 laboratories, sourced from the official SLM price list
-- (slm-xizmatlar-narxlari.md, provided by the client). The
-- Elektromagnit moslashuvchanlik (EMC) lab's services already exist in
-- production (created manually via the admin panel) and are
-- intentionally NOT touched here.
--
-- Uses INSERT ... ON CONFLICT (slug) DO NOTHING on "Service" so this
-- migration is safe even if a matching slug already exists for any
-- reason -- it will never fail the whole batch or duplicate a row.
-- Each "Price" row's serviceId is resolved via a slug subquery instead
-- of a captured id, so it always points at whichever Service row ends
-- up existing (freshly inserted here, or pre-existing).

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('7f9581fb-3127-43be-8607-28f9c5fb6330', 'slm-sinov-ele-avtomobil-akkumlyatorlari', 'Avtomobil akkumlyatorlari sinovi', 'Испытание автомобильных аккумуляторов', 'Testing of automotive batteries', 'Avtomobil akkumlyatorlari sinovi', 'Elektr xavfsizligi va sifat ko''rsatgichlari bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'elektrotexnika'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '0f5ff81f-125a-4f5b-8be4-27d4c21ba1db', id, 502500, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-ele-avtomobil-akkumlyatorlari' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-ele-avtomobil-akkumlyatorlari'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('b47db308-b741-4314-b089-f7a215792b4a', 'slm-sinov-ele-elektrodvigatel-elektr-ehtiyot-qismlari', 'Elektrodvigatellar, avto-traktor elektr ehtiyot qismlari, boshqa turdagi akkumlyatorlar, rele, invertorlar, patronlar, kommutatsiya qurilmalari sinovi', 'Испытание электродвигателей, авто-тракторных электрозапчастей, аккумуляторов других видов, реле, инверторов, патронов, коммутационных устройств', 'Testing of electric motors, auto-tractor electrical spare parts, other types of batteries, relays, inverters, sockets, switching devices', 'Elektrodvigatellar, avto-traktor elektr ehtiyot qismlari, boshqa turdagi akkumlyatorlar, rele, invertorlar, patronlar, kommutatsiya qurilmalari sinovi', 'Elektr xavfsizligi va sifat ko''rsatgichlari bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'elektrotexnika'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT 'f115a191-eedd-4034-ac12-da97b25e889b', id, 335000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-ele-elektrodvigatel-elektr-ehtiyot-qismlari' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-ele-elektrodvigatel-elektr-ehtiyot-qismlari'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('2658f8e9-9699-44f7-9ebc-c5cf5be12340', 'slm-sinov-ele-elektr-lampalar-yoritgichlar', 'Elektr lampalar, yoritgichlar va ular uchun elektr qurilmalari sinovi', 'Испытание электроламп, светильников и электроустройств для них', 'Testing of electric lamps, luminaires and electrical devices for them', 'Elektr lampalar, yoritgichlar va ular uchun elektr qurilmalari sinovi', 'Elektr xavfsizligi va sifat ko''rsatgichlari bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'elektrotexnika'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '57c7b8f2-1ae4-4559-bc4e-7ec6d0c0737e', id, 335000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-ele-elektr-lampalar-yoritgichlar' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-ele-elektr-lampalar-yoritgichlar'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('3cdf8899-0e6f-48de-8b92-36e38f2a940b', 'slm-sinov-ele-fotoelektrik-modul-quyosh-paneli', 'Fotoelektrik modul (quyosh paneli) larini elektr xavfsizlik ko''rsatgichlari bo''yicha sinov', 'Испытание фотоэлектрических модулей (солнечных панелей) по показателям электробезопасности', 'Testing of photovoltaic modules (solar panels) for electrical safety indicators', 'Fotoelektrik modul (quyosh paneli) larini elektr xavfsizlik ko''rsatgichlari bo''yicha sinov', 'Elektr xavfsizligi va sifat ko''rsatgichlari bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'elektrotexnika'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '967cad7e-994c-4987-9cc1-954218ccd2b5', id, 4020000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-ele-fotoelektrik-modul-quyosh-paneli' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-ele-fotoelektrik-modul-quyosh-paneli'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('8bc5e742-b728-4ccd-a594-360f280391fb', 'slm-sinov-ele-kabellar-simlar', 'Kabellar, simlar va shu kabilar sinovi', 'Испытание кабелей, проводов и им подобных изделий', 'Testing of cables, wires and similar products', 'Kabellar, simlar va shu kabilar sinovi', 'Elektr xavfsizligi va sifat ko''rsatgichlari bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'elektrotexnika'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '9b08ccc9-5d9b-4682-b59c-d48138fb2fa9', id, 502500, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-ele-kabellar-simlar' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-ele-kabellar-simlar'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('5303cc76-0070-49c0-b58d-df72c225fef0', 'slm-sinov-ele-maishiy-elektr-jihozlar-audio-video', 'Maishiy elektr jihozlar, audio, video va shu kabi elektron apparatlar, axborot texnologiyalari va ofis uskunalari, qo''l elektr uskunalari sinovi', 'Испытание бытовых электроприборов, аудио-, видео- и подобной электронной аппаратуры, оборудования информационных технологий и офисной техники, ручного электроинструмента', 'Testing of household electrical appliances, audio, video and similar electronic apparatus, information technology and office equipment, hand-held electric tools', 'Maishiy elektr jihozlar, audio, video va shu kabi elektron apparatlar, axborot texnologiyalari va ofis uskunalari, qo''l elektr uskunalari sinovi', 'Elektr xavfsizligi va sifat ko''rsatgichlari bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'elektrotexnika'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '995d80a3-7504-4aeb-88da-7e3ef5db92e8', id, 335000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-ele-maishiy-elektr-jihozlar-audio-video' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-ele-maishiy-elektr-jihozlar-audio-video'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('0a6bd6da-46c5-4e3c-89d9-31b862120791', 'slm-sinov-ele-ornatilgan-joyda-sinov', 'O''rnatilgan joyda sinovlarni o''tkazish', 'Проведение испытаний на месте установки', 'On-site testing at the installation location', 'O''rnatilgan joyda sinovlarni o''tkazish', 'Elektr xavfsizligi va sifat ko''rsatgichlari bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'elektrotexnika'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '481c0ec1-17d9-440a-b06a-bcbe84590282', id, 1005000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-ele-ornatilgan-joyda-sinov' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-ele-ornatilgan-joyda-sinov'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('6fd9d8ea-918d-457b-86dd-9d3b8f4333f9', 'slm-sinov-ele-tibbiyot-laboratoriya-qurilmalari', 'Tibbiyot va laboratoriya qurilmalari, nazorat va o''lchash asboblari, o''lchov vositalari sinovi', 'Испытание медицинского и лабораторного оборудования, контрольно-измерительных приборов, средств измерений', 'Testing of medical and laboratory equipment, control and measuring instruments, measuring devices', 'Tibbiyot va laboratoriya qurilmalari, nazorat va o''lchash asboblari, o''lchov vositalari sinovi', 'Elektr xavfsizligi va sifat ko''rsatgichlari bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'elektrotexnika'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT 'c2faf677-e871-49b3-9e3d-d238c7615965', id, 502500, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-ele-tibbiyot-laboratoriya-qurilmalari' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-ele-tibbiyot-laboratoriya-qurilmalari'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('ce66dd88-6944-419d-b947-8bdb8e7c7129', 'slm-sinov-ele-elektromobil-gibrid-avtotransport', 'Elektromobil va gibrid avtotransport vositalari elektr xavfsizligi sinovi', 'Испытание электробезопасности электромобилей и гибридных автотранспортных средств', 'Electrical safety testing of electric and hybrid vehicles', 'Elektromobil va gibrid avtotransport vositalari elektr xavfsizligi sinovi', 'Elektr xavfsizligi va sifat ko''rsatgichlari bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'elektrotexnika'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT 'b57a4f9c-de06-4163-82bc-511e3e588670', id, 1005000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-ele-elektromobil-gibrid-avtotransport' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-ele-elektromobil-gibrid-avtotransport'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('522cf80b-2967-4a4e-96c4-0c32394f4944', 'slm-sinov-ele-lift-eskalator-ornatilgan-joyda', 'Lift va eskalatorlarni o''rnatilgan joyda sinovi', 'Испытание лифтов и эскалаторов на месте установки', 'On-site testing of elevators and escalators', 'Lift va eskalatorlarni o''rnatilgan joyda sinovi', 'Elektr xavfsizligi va sifat ko''rsatgichlari bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'elektrotexnika'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '63c6f8b7-c333-4b7c-a465-800c9fc0698d', id, 670000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-ele-lift-eskalator-ornatilgan-joyda' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-ele-lift-eskalator-ornatilgan-joyda'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('2db09699-64d1-4a2d-9f65-0b094f4b59de', 'slm-sinov-ele-akustika-shovqin', 'Akustika (shovqin) sinovi', 'Испытание акустики (шума)', 'Acoustic (noise) testing', 'Akustika (shovqin) sinovi', 'Elektr xavfsizligi va sifat ko''rsatgichlari bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'elektrotexnika'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT 'fdd40e50-14de-47fa-bf89-55c3bc98b1e5', id, 2010000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-ele-akustika-shovqin' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-ele-akustika-shovqin'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('656b5e0f-8293-4a8b-9f59-458705361e3f', 'slm-sinov-ele-xizmat-safari-xarajatlari', 'Xizmat safari xarajatlari (har bir soat uchun)', 'Расходы на служебную командировку (за каждый час)', 'Business travel expenses (per hour)', 'Xizmat safari xarajatlari (har bir soat uchun)', 'Elektr xavfsizligi va sifat ko''rsatgichlari bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'elektrotexnika'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT 'f15fb6ee-be97-4193-beed-a1c6ce16a0e7', id, 335000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-ele-xizmat-safari-xarajatlari' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-ele-xizmat-safari-xarajatlari'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('1dd61595-e8a3-4dee-9997-aa44cbcc74d6', 'slm-sinov-eef-konditsioner-energiya-samaradorligi', 'Konditsioner mahsulotlarining energiya samaradorligini aniqlash', 'Определение энергоэффективности кондиционеров', 'Determination of energy efficiency of air conditioners', 'Konditsioner mahsulotlarining energiya samaradorligini aniqlash', 'Energiya samaradorligi ko''rsatgichlari bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'energiya-samaradorligi'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '4f713a67-b68a-49a5-9145-e0af13b93be3', id, 4020000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-eef-konditsioner-energiya-samaradorligi' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-eef-konditsioner-energiya-samaradorligi'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('067d7605-4277-4a5e-8b15-29da2fecabd0', 'slm-sinov-eef-muzlatgich-energiya-samaradorligi', 'Muzlatgich mahsulotlarining energiya samaradorligini aniqlash', 'Определение энергоэффективности холодильников', 'Determination of energy efficiency of refrigerators', 'Muzlatgich mahsulotlarining energiya samaradorligini aniqlash', 'Energiya samaradorligi ko''rsatgichlari bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'energiya-samaradorligi'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '9a5c960f-47d2-44b5-b002-a45732e5f717', id, 4422000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-eef-muzlatgich-energiya-samaradorligi' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-eef-muzlatgich-energiya-samaradorligi'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('5a9fd379-176e-4955-8849-4a131719f23b', 'slm-sinov-eef-kir-yuvish-mashinasi-1kg', 'Kir yuvish mashinasi (1 kg) energiya samaradorligini aniqlash', 'Определение энергоэффективности стиральной машины (1 кг)', 'Determination of energy efficiency of washing machine (1 kg)', 'Kir yuvish mashinasi (1 kg) energiya samaradorligini aniqlash', 'Energiya samaradorligi ko''rsatgichlari bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'energiya-samaradorligi'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '83b6fff2-7bd5-4993-ac7a-0a28b7e38bae', id, 14070000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-eef-kir-yuvish-mashinasi-1kg' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-eef-kir-yuvish-mashinasi-1kg'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('6ca86409-21e1-4ff1-8223-c2e2d7b45840', 'slm-sinov-eef-kir-yuvish-mashinasi-2kg', 'Kir yuvish mashinasi (2 kg) energiya samaradorligini aniqlash', 'Определение энергоэффективности стиральной машины (2 кг)', 'Determination of energy efficiency of washing machine (2 kg)', 'Kir yuvish mashinasi (2 kg) energiya samaradorligini aniqlash', 'Energiya samaradorligi ko''rsatgichlari bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'energiya-samaradorligi'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT 'd956ca2f-869b-4b05-8dec-50cc3539211d', id, 14103500, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-eef-kir-yuvish-mashinasi-2kg' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-eef-kir-yuvish-mashinasi-2kg'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('9320c2aa-5e1e-48c7-aca7-7141db88e2df', 'slm-sinov-eef-kir-yuvish-mashinasi-3kg', 'Kir yuvish mashinasi (3 kg) energiya samaradorligini aniqlash', 'Определение энергоэффективности стиральной машины (3 кг)', 'Determination of energy efficiency of washing machine (3 kg)', 'Kir yuvish mashinasi (3 kg) energiya samaradorligini aniqlash', 'Energiya samaradorligi ko''rsatgichlari bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'energiya-samaradorligi'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT 'f81c4324-8463-4a42-bb5c-32b89e87d7ef', id, 15577500, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-eef-kir-yuvish-mashinasi-3kg' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-eef-kir-yuvish-mashinasi-3kg'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('deef4887-d169-4a3f-82bf-bc2612fde389', 'slm-sinov-eef-kir-yuvish-mashinasi-4kg', 'Kir yuvish mashinasi (4 kg) energiya samaradorligini aniqlash', 'Определение энергоэффективности стиральной машины (4 кг)', 'Determination of energy efficiency of washing machine (4 kg)', 'Kir yuvish mashinasi (4 kg) energiya samaradorligini aniqlash', 'Energiya samaradorligi ko''rsatgichlari bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'energiya-samaradorligi'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT 'a8ccca28-5079-473e-9c04-1cd267ed346c', id, 17085000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-eef-kir-yuvish-mashinasi-4kg' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-eef-kir-yuvish-mashinasi-4kg'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('d5ec0a71-e5fe-441a-b67b-dad69b79aa61', 'slm-sinov-eef-kir-yuvish-mashinasi-5kg', 'Kir yuvish mashinasi (5 kg) energiya samaradorligini aniqlash', 'Определение энергоэффективности стиральной машины (5 кг)', 'Determination of energy efficiency of washing machine (5 kg)', 'Kir yuvish mashinasi (5 kg) energiya samaradorligini aniqlash', 'Energiya samaradorligi ko''rsatgichlari bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'energiya-samaradorligi'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '853e74f8-8d92-4148-baab-24ebf0ff9c77', id, 18592500, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-eef-kir-yuvish-mashinasi-5kg' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-eef-kir-yuvish-mashinasi-5kg'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('b4ebef77-db06-4a30-85e2-4f02a9ae89b3', 'slm-sinov-eef-kir-yuvish-mashinasi-6kg', 'Kir yuvish mashinasi (6 kg) energiya samaradorligini aniqlash', 'Определение энергоэффективности стиральной машины (6 кг)', 'Determination of energy efficiency of washing machine (6 kg)', 'Kir yuvish mashinasi (6 kg) energiya samaradorligini aniqlash', 'Energiya samaradorligi ko''rsatgichlari bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'energiya-samaradorligi'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT 'e22f2c62-3736-40ac-b2ad-21d49b2652a9', id, 20100000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-eef-kir-yuvish-mashinasi-6kg' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-eef-kir-yuvish-mashinasi-6kg'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('d8fe1e71-f0a0-4e4f-8827-7d0b4d0177fc', 'slm-sinov-eef-kir-yuvish-mashinasi-7kg', 'Kir yuvish mashinasi (7 kg) energiya samaradorligini aniqlash', 'Определение энергоэффективности стиральной машины (7 кг)', 'Determination of energy efficiency of washing machine (7 kg)', 'Kir yuvish mashinasi (7 kg) energiya samaradorligini aniqlash', 'Energiya samaradorligi ko''rsatgichlari bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'energiya-samaradorligi'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT 'c3efd447-66fe-4890-8d5a-a5970077c94f', id, 21607500, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-eef-kir-yuvish-mashinasi-7kg' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-eef-kir-yuvish-mashinasi-7kg'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('22861537-d731-4457-adf8-d7372cdafdaf', 'slm-sinov-eef-kir-yuvish-mashinasi-8kg', 'Kir yuvish mashinasi (8 kg) energiya samaradorligini aniqlash', 'Определение энергоэффективности стиральной машины (8 кг)', 'Determination of energy efficiency of washing machine (8 kg)', 'Kir yuvish mashinasi (8 kg) energiya samaradorligini aniqlash', 'Energiya samaradorligi ko''rsatgichlari bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'energiya-samaradorligi'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '0490e0f4-be0c-49c4-92e3-e14a003245d3', id, 23115000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-eef-kir-yuvish-mashinasi-8kg' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-eef-kir-yuvish-mashinasi-8kg'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('adba3fa1-878e-44b7-95e5-3d0074107736', 'slm-sinov-eef-kir-yuvish-mashinasi-9kg', 'Kir yuvish mashinasi (9 kg) energiya samaradorligini aniqlash', 'Определение энергоэффективности стиральной машины (9 кг)', 'Determination of energy efficiency of washing machine (9 kg)', 'Kir yuvish mashinasi (9 kg) energiya samaradorligini aniqlash', 'Energiya samaradorligi ko''rsatgichlari bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'energiya-samaradorligi'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '749cef36-6ab2-43a1-9d0f-a8227ea69df9', id, 24622500, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-eef-kir-yuvish-mashinasi-9kg' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-eef-kir-yuvish-mashinasi-9kg'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('11e7b7c0-92e8-465e-a24b-25534c741d9a', 'slm-sinov-eef-kir-yuvish-mashinasi-10kg', 'Kir yuvish mashinasi (10 kg) energiya samaradorligini aniqlash', 'Определение энергоэффективности стиральной машины (10 кг)', 'Determination of energy efficiency of washing machine (10 kg)', 'Kir yuvish mashinasi (10 kg) energiya samaradorligini aniqlash', 'Energiya samaradorligi ko''rsatgichlari bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'energiya-samaradorligi'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '17c69323-6165-4fc8-b128-fac49eb5ea62', id, 26130000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-eef-kir-yuvish-mashinasi-10kg' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-eef-kir-yuvish-mashinasi-10kg'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('472d7804-7fa1-4ce5-a0d6-0bfed76fc464', 'slm-sinov-eef-kir-yuvish-mashinasi-11kg', 'Kir yuvish mashinasi (11 kg) energiya samaradorligini aniqlash', 'Определение энергоэффективности стиральной машины (11 кг)', 'Determination of energy efficiency of washing machine (11 kg)', 'Kir yuvish mashinasi (11 kg) energiya samaradorligini aniqlash', 'Energiya samaradorligi ko''rsatgichlari bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'energiya-samaradorligi'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT 'fdbadac3-d6aa-484d-af62-023317d4c618', id, 27604000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-eef-kir-yuvish-mashinasi-11kg' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-eef-kir-yuvish-mashinasi-11kg'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('3627629b-01b3-4f36-a702-557cbc0a08d9', 'slm-sinov-eef-kir-yuvish-mashinasi-12kg', 'Kir yuvish mashinasi (12 kg) energiya samaradorligini aniqlash', 'Определение энергоэффективности стиральной машины (12 кг)', 'Determination of energy efficiency of washing machine (12 kg)', 'Kir yuvish mashinasi (12 kg) energiya samaradorligini aniqlash', 'Energiya samaradorligi ko''rsatgichlari bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'energiya-samaradorligi'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT 'c6be7335-bf18-4e51-89db-2f9fb515c821', id, 29145000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-eef-kir-yuvish-mashinasi-12kg' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-eef-kir-yuvish-mashinasi-12kg'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('cd25b045-bd8b-4b1c-990b-4fc3d10edb69', 'slm-sinov-eef-kir-yuvish-mashinasi-13kg', 'Kir yuvish mashinasi (13 kg) energiya samaradorligini aniqlash', 'Определение энергоэффективности стиральной машины (13 кг)', 'Determination of energy efficiency of washing machine (13 kg)', 'Kir yuvish mashinasi (13 kg) energiya samaradorligini aniqlash', 'Energiya samaradorligi ko''rsatgichlari bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'energiya-samaradorligi'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT 'a10c0f59-3d1f-4360-b446-29e036926d33', id, 30619000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-eef-kir-yuvish-mashinasi-13kg' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-eef-kir-yuvish-mashinasi-13kg'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('bd26dc7e-9174-4cf7-841e-1bb7646feadc', 'slm-sinov-eef-kir-yuvish-mashinasi-14kg', 'Kir yuvish mashinasi (14 kg) energiya samaradorligini aniqlash', 'Определение энергоэффективности стиральной машины (14 кг)', 'Determination of energy efficiency of washing machine (14 kg)', 'Kir yuvish mashinasi (14 kg) energiya samaradorligini aniqlash', 'Energiya samaradorligi ko''rsatgichlari bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'energiya-samaradorligi'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '79d360ae-d2d9-4296-86b2-734b0d336593', id, 32160000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-eef-kir-yuvish-mashinasi-14kg' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-eef-kir-yuvish-mashinasi-14kg'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('17a4da29-891f-465a-850c-ff17b834368c', 'slm-sinov-eef-kir-yuvish-mashinasi-15kg', 'Kir yuvish mashinasi (15 kg) energiya samaradorligini aniqlash', 'Определение энергоэффективности стиральной машины (15 кг)', 'Determination of energy efficiency of washing machine (15 kg)', 'Kir yuvish mashinasi (15 kg) energiya samaradorligini aniqlash', 'Energiya samaradorligi ko''rsatgichlari bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'energiya-samaradorligi'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '85ce0bb1-290f-4447-afc6-ddf7336c3b82', id, 33667500, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-eef-kir-yuvish-mashinasi-15kg' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-eef-kir-yuvish-mashinasi-15kg'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('644873d9-1cf5-4c1c-8eda-d0523e615a06', 'slm-sinov-eef-boyler-energiya-samaradorligi', 'Boylerlarning energiya samaradorligini aniqlash', 'Определение энергоэффективности бойлеров', 'Determination of energy efficiency of boilers (water heaters)', 'Boylerlarning energiya samaradorligini aniqlash', 'Energiya samaradorligi ko''rsatgichlari bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'energiya-samaradorligi'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '862d82e5-b35d-48ba-9786-69234ae1eb08', id, 6231000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-eef-boyler-energiya-samaradorligi' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-eef-boyler-energiya-samaradorligi'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('f0cd6dcf-1225-4b1b-83c2-63140431a2ce', 'slm-sinov-pol-gofra-karton-qutilar', 'Gofra karton qutilar sinovi', 'Испытание гофрированных картонных коробок', 'Testing of corrugated cardboard boxes', 'Gofra karton qutilar sinovi', 'Polimer mahsulot sifati va xavfsizligi bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'polimer'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '4c65aa8d-c4cd-49e8-8f8a-c657ac2b56a5', id, 201000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-pol-gofra-karton-qutilar' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-pol-gofra-karton-qutilar'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('5d24e87a-ca79-4b40-841a-aac18193efe1', 'slm-sinov-pol-karton-karobka-qogoz-mahsulotlari', 'Karton karobkalar, oziq-ovqat mahsulotlarini qadoqlashda ishlatiladigan qog''ozlar, kalka, pachka, qog''ozdan bir martalik idishlar, sanitar-gigiyena uchun ishlatiladigan qog''ozlar va shu turdagi mahsulotlar sinovi', 'Испытание картонных коробок, бумаги для упаковки пищевых продуктов, кальки, пачек, одноразовой бумажной посуды, санитарно-гигиенической бумаги и подобных изделий', 'Testing of cardboard boxes, paper for food packaging, tracing paper, packs, disposable paper tableware, sanitary-hygienic paper and similar products', 'Karton karobkalar, oziq-ovqat mahsulotlarini qadoqlashda ishlatiladigan qog''ozlar, kalka, pachka, qog''ozdan bir martalik idishlar, sanitar-gigiyena uchun ishlatiladigan qog''ozlar va shu turdagi mahsulotlar sinovi', 'Polimer mahsulot sifati va xavfsizligi bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'polimer'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT 'b389fe74-e843-44cc-9c87-15e3fa1e0665', id, 201000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-pol-karton-karobka-qogoz-mahsulotlari' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-pol-karton-karobka-qogoz-mahsulotlari'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('233715d6-ddd2-4f65-8925-e3aa44de91d8', 'slm-sinov-pol-oboy-linoleum-toshamalar', 'Oboy, linoleum va to''shamalar, polimer listlar va shu turdagi mahsulotlar sinovi', 'Испытание обоев, линолеума и напольных покрытий, полимерных листов и подобных изделий', 'Testing of wallpaper, linoleum and floor coverings, polymer sheets and similar products', 'Oboy, linoleum va to''shamalar, polimer listlar va shu turdagi mahsulotlar sinovi', 'Polimer mahsulot sifati va xavfsizligi bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'polimer'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '78721bc0-732d-43c5-9410-616ad89a34f8', id, 201000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-pol-oboy-linoleum-toshamalar' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-pol-oboy-linoleum-toshamalar'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('054b3eba-c29c-463a-b742-9cc41540df2c', 'slm-sinov-pol-plastmassa-mahsulotlari', 'Plastmassa mahsulotlari, plastmassadan tiqinlash vositalari va qopqoqlar, tublar, bir martalik polimer idish-tovoqlar, preformalar va shu turdagi mahsulotlar sinovi', 'Испытание пластмассовых изделий, пластмассовых укупорочных средств и крышек, туб, одноразовой полимерной посуды, преформ и подобных изделий', 'Testing of plastic products, plastic closures and caps, tubes, disposable polymer tableware, preforms and similar products', 'Plastmassa mahsulotlari, plastmassadan tiqinlash vositalari va qopqoqlar, tublar, bir martalik polimer idish-tovoqlar, preformalar va shu turdagi mahsulotlar sinovi', 'Polimer mahsulot sifati va xavfsizligi bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'polimer'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT 'b8e8176f-9223-4a1c-ad4e-71b41a1ba7da', id, 201000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-pol-plastmassa-mahsulotlari' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-pol-plastmassa-mahsulotlari'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('7595c848-f8a3-4ab9-a4c6-cb84d6124a89', 'slm-sinov-pol-plastmassa-truba-1000-soatlik', 'Plastmassa trubalarning uzoq muddatli (1000 soatlik) sinovi', 'Долгосрочное (1000-часовое) испытание пластмассовых труб', 'Long-term (1000-hour) testing of plastic pipes', 'Plastmassa trubalarning uzoq muddatli (1000 soatlik) sinovi', 'Polimer mahsulot sifati va xavfsizligi bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'polimer'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '71b7e9c6-5356-4131-93b0-519f58572f34', id, 1005000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-pol-plastmassa-truba-1000-soatlik' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-pol-plastmassa-truba-1000-soatlik'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('d6bbe106-546e-40f1-860e-4786d11b25a4', 'slm-sinov-pol-plyonka-mahsulotlari-paketlar-lenta', 'Plyonka mahsulotlari, xo''jalik paketlari, FUM lenta, polimer va polipropilen qoplar, polimer, dekorativ, yopishqoq, himoyalovchi va qadoqlash lentalari, etiketka va naklaykalar, izolenta va shu turdagi boshqa mahsulotlar sinovi', 'Испытание плёночных изделий, хозяйственных пакетов, ФУМ-ленты, полимерных и полипропиленовых мешков, полимерных, декоративных, клейких, защитных и упаковочных лент, этикеток и наклеек, изоленты и подобных изделий', 'Testing of film products, household bags, PTFE tape, polymer and polypropylene sacks, polymer, decorative, adhesive, protective and packaging tapes, labels and stickers, insulating tape and similar products', 'Plyonka mahsulotlari, xo''jalik paketlari, FUM lenta, polimer va polipropilen qoplar, polimer, dekorativ, yopishqoq, himoyalovchi va qadoqlash lentalari, etiketka va naklaykalar, izolenta va shu turdagi boshqa mahsulotlar sinovi', 'Polimer mahsulot sifati va xavfsizligi bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'polimer'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT 'd3b3c235-3d28-4bd8-861f-6f9fbb93a625', id, 201000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-pol-plyonka-mahsulotlari-paketlar-lenta' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-pol-plyonka-mahsulotlari-paketlar-lenta'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('99917dff-72c9-44e3-b1e8-3a2deab4cec7', 'slm-sinov-pol-poligrafiya-mahsulotlari', 'Poligrafiya mahsulotlari (daftar, rasm daftar, kundalik, kitob, mulyaj va shu turdagi mahsulotlar) sinovi', 'Испытание полиграфической продукции (тетради, альбомы для рисования, ежедневники, книги, муляжи и подобные изделия)', 'Testing of printing products (notebooks, drawing albums, diaries, books, mockups and similar items)', 'Poligrafiya mahsulotlari (daftar, rasm daftar, kundalik, kitob, mulyaj va shu turdagi mahsulotlar) sinovi', 'Polimer mahsulot sifati va xavfsizligi bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'polimer'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '0066b940-4af1-4af7-ae1d-802c3b60ba8e', id, 201000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-pol-poligrafiya-mahsulotlari' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-pol-poligrafiya-mahsulotlari'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('5356efe0-b35b-4ec0-8635-2a3dca95416d', 'slm-sinov-pol-polimer-rezina-shlang-truba-fiting', 'Polimer, rezina, gofra shlang, tomchilab sug''orishda ishlatiladigan truba va shlanglar, yuqori bosim va oqava uchun ishlatiladigan trubalar, fitinglar (PE, PP, PVX) va shu kabilar sinovi', 'Испытание полимерных, резиновых, гофрированных шлангов, труб и шлангов для капельного орошения, труб для высокого давления и стоков, фитингов (ПЭ, ПП, ПВХ) и им подобных изделий', 'Testing of polymer, rubber and corrugated hoses, pipes and hoses used for drip irrigation, pipes for high pressure and drainage, fittings (PE, PP, PVC) and similar products', 'Polimer, rezina, gofra shlang, tomchilab sug''orishda ishlatiladigan truba va shlanglar, yuqori bosim va oqava uchun ishlatiladigan trubalar, fitinglar (PE, PP, PVX) va shu kabilar sinovi', 'Polimer mahsulot sifati va xavfsizligi bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'polimer'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT 'bd813399-c8ee-4dfd-88ed-c0a11efe8718', id, 502500, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-pol-polimer-rezina-shlang-truba-fiting' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-pol-polimer-rezina-shlang-truba-fiting'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('38437332-94ac-437e-be33-be5967735988', 'slm-sinov-pol-porolon-gubka-penopoliuretan', 'Porolon, gubka (penopoliuretan) sinovi', 'Испытание поролона, губки (пенополиуретана)', 'Testing of foam rubber, sponge (polyurethane foam)', 'Porolon, gubka (penopoliuretan) sinovi', 'Polimer mahsulot sifati va xavfsizligi bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'polimer'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '21a5b322-3c9b-4de9-a0ec-df7e09899e9a', id, 201000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-pol-porolon-gubka-penopoliuretan' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-pol-porolon-gubka-penopoliuretan'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('4bd06171-efc2-4401-b72f-73ae8e71f826', 'slm-sinov-pol-qadoqlash-alyuminiy-folga', 'Qadoqlash uchun alyuminiy folgalar sinovi', 'Испытание алюминиевой фольги для упаковки', 'Testing of aluminum foil for packaging', 'Qadoqlash uchun alyuminiy folgalar sinovi', 'Polimer mahsulot sifati va xavfsizligi bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'polimer'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT 'aca3422f-0938-49b2-8766-a09588a729f0', id, 201000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-pol-qadoqlash-alyuminiy-folga' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-pol-qadoqlash-alyuminiy-folga'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('ba59e83a-c46f-4419-a44e-d356f73b005e', 'slm-sinov-pol-sumka-chamadon-maktab-portfeli', 'Sumka, chamadon, maktab portfeli, papka va shu turdagi mahsulotlar sinovi', 'Испытание сумок, чемоданов, школьных портфелей, папок и подобных изделий', 'Testing of bags, suitcases, school satchels, folders and similar products', 'Sumka, chamadon, maktab portfeli, papka va shu turdagi mahsulotlar sinovi', 'Polimer mahsulot sifati va xavfsizligi bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'polimer'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '3536a159-a9c5-4a5c-8c7d-4e1c0d8a17d2', id, 201000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-pol-sumka-chamadon-maktab-portfeli' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-pol-sumka-chamadon-maktab-portfeli'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('a757233a-19b8-4492-b4f1-2b0ec67e9123', 'slm-sinov-pol-temir-zanglamas-idish-tovoq', 'Temir idish-tovoq mahsulotlari, zanglamas metaldan idish-tovoq mahsulotlari va shu turdagi mahsulotlar sinovi', 'Испытание изделий железной посуды, посуды из нержавеющего металла и подобных изделий', 'Testing of iron tableware products, stainless steel tableware and similar products', 'Temir idish-tovoq mahsulotlari, zanglamas metaldan idish-tovoq mahsulotlari va shu turdagi mahsulotlar sinovi', 'Polimer mahsulot sifati va xavfsizligi bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'polimer'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '80c5bcb5-3bb3-4c68-96e1-6f399ddec598', id, 201000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-pol-temir-zanglamas-idish-tovoq' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-pol-temir-zanglamas-idish-tovoq'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('6b063a5b-c102-404e-b662-aea12bcb8577', 'slm-sinov-pol-issiqlik-izolyatsiyasi-mahsulotlari', 'Issiqlik izolyatsiyasi uchun ishlatiladigan mahsulotlar sinovi', 'Испытание изделий, используемых для теплоизоляции', 'Testing of products used for thermal insulation', 'Issiqlik izolyatsiyasi uchun ishlatiladigan mahsulotlar sinovi', 'Polimer mahsulot sifati va xavfsizligi bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'polimer'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT 'bd948a9a-c03d-400c-955a-4619c8125503', id, 201000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-pol-issiqlik-izolyatsiyasi-mahsulotlari' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-pol-issiqlik-izolyatsiyasi-mahsulotlari'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('3a0c7e05-b42a-42b2-85d4-1296f1dac14c', 'slm-sinov-pol-polimer-quvur-d500-bosimga-chidamlilik', 'D-500 va undan yuqori o''lchamli polimer quvurlarning 1000 soatlik doimiy ichki bosimga chidamliligi sinovi', '1000-часовое испытание стойкости к постоянному внутреннему давлению полимерных труб диаметром D-500 и выше', '1000-hour resistance test to constant internal pressure for polymer pipes with diameter D-500 and above', 'D-500 va undan yuqori o''lchamli polimer quvurlarning 1000 soatlik doimiy ichki bosimga chidamliligi sinovi', 'Polimer mahsulot sifati va xavfsizligi bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'polimer'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '7e566cd1-ee8a-482e-93f6-8d6606344ee7', id, 3350000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-pol-polimer-quvur-d500-bosimga-chidamlilik' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-pol-polimer-quvur-d500-bosimga-chidamlilik'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('e17908f3-513b-4f4c-8765-1f874dd8692a', 'slm-sinov-tek-iplar', 'Iplar sinovi', 'Испытание нитей (пряжи)', 'Testing of yarns/threads', 'Iplar sinovi', 'Yengil sanoat mahsuloti sifati va xavfsizligi bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'yengil-sanoat'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '6456d246-a354-45f9-a8ee-8a734caed27d', id, 201000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-tek-iplar' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-tek-iplar'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('9b0836a4-cacf-485e-8196-2dbe59dddda5', 'slm-sinov-tek-doka-gigiyenik-paxta', 'Maishiy va tibbiy doka, gigiyenik paxta sinovi', 'Испытание бытовой и медицинской марли, гигиенической ваты', 'Testing of household and medical gauze, hygienic cotton wool', 'Maishiy va tibbiy doka, gigiyenik paxta sinovi', 'Yengil sanoat mahsuloti sifati va xavfsizligi bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'yengil-sanoat'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '392f85cb-c4dc-437d-b26c-3ffcb4da4db0', id, 201000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-tek-doka-gigiyenik-paxta' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-tek-doka-gigiyenik-paxta'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('e3b07357-ebb5-4f35-8553-273a36384e03', 'slm-sinov-tek-matolar', 'Matolar sinovi', 'Испытание тканей', 'Testing of fabrics', 'Matolar sinovi', 'Yengil sanoat mahsuloti sifati va xavfsizligi bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'yengil-sanoat'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT 'c462b7a1-c8fd-45e8-bbac-3f163d4eec99', id, 201000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-tek-matolar' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-tek-matolar'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('dd4d9044-8bd9-41fc-9d57-123930cef2b7', 'slm-sinov-tek-maxsus-himoya-kiyimlari', 'Maxsus himoya kiyimlari sinovi', 'Испытание специальной защитной одежды', 'Testing of special protective clothing', 'Maxsus himoya kiyimlari sinovi', 'Yengil sanoat mahsuloti sifati va xavfsizligi bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'yengil-sanoat'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '6390cee2-4c9b-454e-95df-2681a442e2a4', id, 201000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-tek-maxsus-himoya-kiyimlari' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-tek-maxsus-himoya-kiyimlari'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('fca094b9-f859-470f-a37c-1f53429d0ef3', 'slm-sinov-tek-toqimasiz-mato-yuz-niqobi', 'To''qimasiz matodan gigiyenik yuz niqobi sinovi', 'Испытание гигиенических масок для лица из нетканого материала', 'Testing of hygienic face masks made of non-woven fabric', 'To''qimasiz matodan gigiyenik yuz niqobi sinovi', 'Yengil sanoat mahsuloti sifati va xavfsizligi bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'yengil-sanoat'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT 'bb7c81a7-faad-459e-97db-8215fd20cbef', id, 201000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-tek-toqimasiz-mato-yuz-niqobi' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-tek-toqimasiz-mato-yuz-niqobi'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('3e35110e-40f6-4bcb-97b4-d85ba7cd2e7d', 'slm-sinov-tek-palatkalar', 'Palatkalar sinovi', 'Испытание палаток', 'Testing of tents', 'Palatkalar sinovi', 'Yengil sanoat mahsuloti sifati va xavfsizligi bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'yengil-sanoat'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT 'a181ac6d-9520-42a2-8548-3422092970de', id, 201000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-tek-palatkalar' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-tek-palatkalar'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('2597c73d-8675-4be4-b6ae-c6e5ff498ce9', 'slm-sinov-tek-poyabzal', 'Poyabzal sinovi', 'Испытание обуви', 'Testing of footwear', 'Poyabzal sinovi', 'Yengil sanoat mahsuloti sifati va xavfsizligi bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'yengil-sanoat'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '1b97de26-9bbe-476f-9a15-1115104d0177', id, 201000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-tek-poyabzal' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-tek-poyabzal'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('86588294-15aa-4616-81a4-21e27d86c021', 'slm-sinov-tek-sanitariya-gigiyenik-mahsulotlar', 'Sanitariya va gigiyenik mahsulotlar sinovi', 'Испытание санитарно-гигиенических изделий', 'Testing of sanitary and hygiene products', 'Sanitariya va gigiyenik mahsulotlar sinovi', 'Yengil sanoat mahsuloti sifati va xavfsizligi bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'yengil-sanoat'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '57915fb0-8114-4fae-aa9d-881fd4d71160', id, 201000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-tek-sanitariya-gigiyenik-mahsulotlar' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-tek-sanitariya-gigiyenik-mahsulotlar'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('8ca5df26-20d5-4281-ae00-b9caf9720fec', 'slm-sinov-tek-sifat-sertifikati', 'Sifat sertifikati (sinovlar o''tkazilgan holatda)', 'Сертификат качества (при проведении испытаний)', 'Quality certificate (when tests are conducted)', 'Sifat sertifikati (sinovlar o''tkazilgan holatda)', 'Yengil sanoat mahsuloti sifati va xavfsizligi bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'yengil-sanoat'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '5f8285be-f7d2-4ec9-ab9d-5be12a913e5c', id, 2010000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-tek-sifat-sertifikati' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-tek-sifat-sertifikati'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('e883c661-aebb-4251-93a0-7ae327eba9ad', 'slm-sinov-tek-tikuv-trikotaj-paypoq-tekstil', 'Tayyor tikuv mahsulotlari, tayyor trikotaj mahsulotlari, paypoq va boshqa turdagi tekstil mahsulotlari sinovi', 'Испытание готовых швейных изделий, готовых трикотажных изделий, носков и других видов текстильных изделий', 'Testing of ready-made sewn goods, ready-made knitwear, socks and other types of textile products', 'Tayyor tikuv mahsulotlari, tayyor trikotaj mahsulotlari, paypoq va boshqa turdagi tekstil mahsulotlari sinovi', 'Yengil sanoat mahsuloti sifati va xavfsizligi bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'yengil-sanoat'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT 'da0b6a62-9967-4baf-b825-07d87f208c6c', id, 201000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-tek-tikuv-trikotaj-paypoq-tekstil' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-tek-tikuv-trikotaj-paypoq-tekstil'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('e067b5b6-096c-4533-8053-3c443d729daf', 'slm-sinov-tek-texnik-topshiriq-asosida-sinov', 'Texnik topshiriqlar asosida tashkil etiladigan sinovlar', 'Испытания, организуемые на основании технического задания', 'Tests organized based on technical specifications', 'Texnik topshiriqlar asosida tashkil etiladigan sinovlar', 'Yengil sanoat mahsuloti sifati va xavfsizligi bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'yengil-sanoat'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT 'bed6de41-aa18-492c-8af2-b0f196852a52', id, 2010000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-tek-texnik-topshiriq-asosida-sinov' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-tek-texnik-topshiriq-asosida-sinov'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('3ac55aa6-dca9-4ba0-9385-a990d4b4232f', 'slm-sinov-tek-toqimachilik-kimyoviy-sinov', 'To''qimachilik mahsulotlarini kimyoviy sinovdan o''tkazish', 'Проведение химического испытания текстильных изделий', 'Chemical testing of textile products', 'To''qimachilik mahsulotlarini kimyoviy sinovdan o''tkazish', 'Yengil sanoat mahsuloti sifati va xavfsizligi bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'yengil-sanoat'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '07ebfedb-e2f6-4ead-bf69-72a7a4e9b0ed', id, 335000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-tek-toqimachilik-kimyoviy-sinov' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-tek-toqimachilik-kimyoviy-sinov'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('64ae22f7-442a-464f-a520-a1f3c8594859', 'slm-sinov-tek-harbiy-kiyim-yotoq-mahsulotlari', 'Harbiylar uchun kiyim-kechak, yotoq mahsulotlari va boshqalar sinovi', 'Испытание обмундирования, постельных принадлежностей и прочего военного назначения', 'Testing of military clothing, bedding products and other items', 'Harbiylar uchun kiyim-kechak, yotoq mahsulotlari va boshqalar sinovi', 'Yengil sanoat mahsuloti sifati va xavfsizligi bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'yengil-sanoat'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '7a6ffb65-0138-4a72-8b0e-9692063d3120', id, 502500, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-tek-harbiy-kiyim-yotoq-mahsulotlari' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-tek-harbiy-kiyim-yotoq-mahsulotlari'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('c4d95960-cca3-4c7a-84a6-e72a12a8b4a9', 'slm-sinov-xbb-formaldegidni-aniqlash', 'Formaldegidni aniqlash', 'Определение формальдегида', 'Determination of formaldehyde', 'Formaldegidni aniqlash', 'Kimyoviy-biologik xavfsizlik ko''rsatgichlari bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'kimyoviy-biologik'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '524a3f14-a1da-43b0-92aa-0fb773c20126', id, 167500, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-xbb-formaldegidni-aniqlash' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-xbb-formaldegidni-aniqlash'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('4bc676e0-82fa-46f0-85ae-92d57e6c14b8', 'slm-sinov-xbb-organoleptik-korsatgichlar', 'Mahsulotlarning organoleptik ko''rsatgichlarini aniqlash', 'Определение органолептических показателей продукции', 'Determination of organoleptic indicators of products', 'Mahsulotlarning organoleptik ko''rsatgichlarini aniqlash', 'Kimyoviy-biologik xavfsizlik ko''rsatgichlari bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'kimyoviy-biologik'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '057fb019-79f1-4a5b-8b22-922583e89ef3', id, 167500, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-xbb-organoleptik-korsatgichlar' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-xbb-organoleptik-korsatgichlar'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('b698e52f-5ecb-46d9-83c0-8c88ddda3a65', 'slm-sinov-xbb-ogir-metallar', 'Og''ir metallar', 'Тяжёлые металлы', 'Heavy metals', 'Og''ir metallar', 'Kimyoviy-biologik xavfsizlik ko''rsatgichlari bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'kimyoviy-biologik'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '5152649b-ea10-4166-8b4b-36bac0399ab4', id, 335000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-xbb-ogir-metallar' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-xbb-ogir-metallar'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('a1f0fb38-1b59-47f6-88ba-98fa3ebc1aeb', 'slm-sinov-xbb-toksikologik-indeks', 'Toksikologik indeks', 'Токсикологический индекс', 'Toxicological index', 'Toksikologik indeks', 'Kimyoviy-biologik xavfsizlik ko''rsatgichlari bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'kimyoviy-biologik'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '36e7d8bd-1b2a-489c-bfe4-44b2a7e8c3d0', id, 335000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-xbb-toksikologik-indeks' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-xbb-toksikologik-indeks'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('d2d41830-6d03-41f0-881b-34d42324e3f8', 'slm-sinov-xbb-uchuvchan-organik-moddalar', 'Uchuvchan organik moddalar', 'Летучие органические соединения', 'Volatile organic compounds', 'Uchuvchan organik moddalar', 'Kimyoviy-biologik xavfsizlik ko''rsatgichlari bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'kimyoviy-biologik'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '1bc7b78a-a1ca-4fb6-a1ce-acf32dd77175', id, 335000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-xbb-uchuvchan-organik-moddalar' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-xbb-uchuvchan-organik-moddalar'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('00b52261-af8f-499d-b4f7-670539692bf8', 'slm-sinov-xbb-rohs-sinov-korsatgichlari', 'RoHS sinov ko''rsatgichlari', 'Показатели испытаний RoHS', 'RoHS test indicators', 'RoHS sinov ko''rsatgichlari', 'Kimyoviy-biologik xavfsizlik ko''rsatgichlari bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'kimyoviy-biologik'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '44a139e4-70fb-4ac3-8e55-c3f308549595', id, 3484000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-xbb-rohs-sinov-korsatgichlari' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-xbb-rohs-sinov-korsatgichlari'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('8a1d51db-1c36-4383-80d6-9d92c77841a2', 'slm-sinov-xbb-allergen-moddalar-miqdori', 'O''yinchoqlar va parfyumeriya mahsulotlarida allergen moddalarning miqdorini aniqlash', 'Определение количества аллергенных веществ в игрушках и парфюмерной продукции', 'Determination of allergenic substance content in toys and perfumery products', 'O''yinchoqlar va parfyumeriya mahsulotlarida allergen moddalarning miqdorini aniqlash', 'Kimyoviy-biologik xavfsizlik ko''rsatgichlari bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'kimyoviy-biologik'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '7aa1a52d-998d-4e68-97cd-002c3717a61f', id, 201000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-xbb-allergen-moddalar-miqdori' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-xbb-allergen-moddalar-miqdori'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('1bd4340f-051a-487e-a40b-3f0167f2485b', 'slm-sinov-igr-bolalar-oyinchoqlari', 'Bolalar o''yinchoqlari sinovi', 'Испытание детских игрушек', 'Testing of children''s toys', 'Bolalar o''yinchoqlari sinovi', 'Bolalar o''yinchoqlari xavfsizligi bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'oyinchoqlar'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '54b3e57d-1670-4fcf-a784-d405a956f770', id, 100500, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-igr-bolalar-oyinchoqlari' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-igr-bolalar-oyinchoqlari'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('2f89770c-504d-4a10-8ec7-449f8d4d588b', 'slm-sinov-igr-shishiriladigan-mahsulotlar', 'Bolalar uchun shishiriladigan va shu turdagi mahsulotlar sinovi', 'Испытание надувных и подобных изделий для детей', 'Testing of inflatable and similar products for children', 'Bolalar uchun shishiriladigan va shu turdagi mahsulotlar sinovi', 'Bolalar o''yinchoqlari xavfsizligi bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'oyinchoqlar'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT 'e1270edb-da3c-4c9f-a2a7-fc7b880f085f', id, 100500, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-igr-shishiriladigan-mahsulotlar' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-igr-shishiriladigan-mahsulotlar'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('73bba43c-55bd-4987-bf24-4a5aa552f568', 'slm-sinov-igr-butilka-banka-oziq-ovqat', 'Butilka va banka (oziq-ovqat mahsulotlari uchun) sinovi', 'Испытание бутылок и банок (для пищевых продуктов)', 'Testing of bottles and jars (for food products)', 'Butilka va banka (oziq-ovqat mahsulotlari uchun) sinovi', 'Bolalar o''yinchoqlari xavfsizligi bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'oyinchoqlar'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '948b7aa3-42c6-481c-b2f0-5ebfb2fc14f8', id, 335000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-igr-butilka-banka-oziq-ovqat' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-igr-butilka-banka-oziq-ovqat'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('003ccba3-f89c-4f07-8ed8-8005ad2ad45d', 'slm-sinov-igr-gugurt', 'Gugurt sinovi', 'Испытание спичек', 'Testing of matches', 'Gugurt sinovi', 'Bolalar o''yinchoqlari xavfsizligi bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'oyinchoqlar'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT 'da16d6b4-d240-4791-bed3-a62e512c5e1d', id, 335000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-igr-gugurt' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-igr-gugurt'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('876ac8d9-21ad-4896-8a0c-220c9b701c71', 'slm-sinov-igr-hojalik-dekorativ-shamlar', 'Ho''jalik va dekorativ shamlar sinovi', 'Испытание хозяйственных и декоративных свечей', 'Testing of household and decorative candles', 'Ho''jalik va dekorativ shamlar sinovi', 'Bolalar o''yinchoqlari xavfsizligi bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'oyinchoqlar'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '8b6da343-6ae1-4637-8647-71e41b4dfc0b', id, 335000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-igr-hojalik-dekorativ-shamlar' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-igr-hojalik-dekorativ-shamlar'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('816df000-d491-4fa2-b4eb-f77977c1a7f3', 'slm-sinov-igr-keramika-farfor-fayans-idishlar', 'Keramika, farfor, fayans idishlar sinovi', 'Испытание керамической, фарфоровой, фаянсовой посуды', 'Testing of ceramic, porcelain, faience tableware', 'Keramika, farfor, fayans idishlar sinovi', 'Bolalar o''yinchoqlari xavfsizligi bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'oyinchoqlar'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '1c8d696e-bf4b-45ce-91a0-b43b42bce463', id, 167500, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-igr-keramika-farfor-fayans-idishlar' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-igr-keramika-farfor-fayans-idishlar'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('842e7743-2880-4f91-8a6f-a511b9893325', 'slm-sinov-igr-laboratoriya-shisha-idishlar', 'Laboratoriya shisha idishlari (flakon, butilka va shu turkumga kiruvchi shisha taralar) sinovi', 'Испытание лабораторной стеклянной посуды (флаконы, бутылки и подобная стеклянная тара)', 'Testing of laboratory glassware (vials, bottles and similar glass containers)', 'Laboratoriya shisha idishlari (flakon, butilka va shu turkumga kiruvchi shisha taralar) sinovi', 'Bolalar o''yinchoqlari xavfsizligi bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'oyinchoqlar'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT 'ae8a6d5a-151c-4123-a990-476ffde482d2', id, 670000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-igr-laboratoriya-shisha-idishlar' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-igr-laboratoriya-shisha-idishlar'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('da1ab85a-3180-40a6-8ed3-ad42fb98fac8', 'slm-sinov-igr-lateksli-sorgich', 'Lateksli bolalar so''rg''ichlari va shu turdagi mahsulotlar sinovi', 'Испытание латексных детских сосок и подобных изделий', 'Testing of latex baby pacifiers and similar products', 'Lateksli bolalar so''rg''ichlari va shu turdagi mahsulotlar sinovi', 'Bolalar o''yinchoqlari xavfsizligi bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'oyinchoqlar'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '92cf92f8-f6fa-464b-8a58-68065eb72226', id, 502500, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-igr-lateksli-sorgich' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-igr-lateksli-sorgich'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('705a5024-a478-4de7-87d9-6ea168d3624e', 'slm-sinov-igr-plastilin-mahsulotlari', 'Plastilin mahsulotlari sinovi', 'Испытание изделий из пластилина', 'Testing of plasticine products', 'Plastilin mahsulotlari sinovi', 'Bolalar o''yinchoqlari xavfsizligi bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'oyinchoqlar'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '4faf2adc-5a35-41c4-b7ef-f727835c6bb2', id, 502500, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-igr-plastilin-mahsulotlari' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-igr-plastilin-mahsulotlari'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('fbbace47-caa9-4db1-9ac4-f2e136466d13', 'slm-sinov-igr-katta-olchamdagi-plastmassa-oyinchoq', 'Plastmassadan katta o''lchamdagi bolalar o''yinchoqlari sinovi', 'Испытание крупногабаритных пластмассовых детских игрушек', 'Testing of large-sized plastic children''s toys', 'Plastmassadan katta o''lchamdagi bolalar o''yinchoqlari sinovi', 'Bolalar o''yinchoqlari xavfsizligi bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'oyinchoqlar'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '3964d901-4828-447c-bcdf-42fa374749cc', id, 167500, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-igr-katta-olchamdagi-plastmassa-oyinchoq' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-igr-katta-olchamdagi-plastmassa-oyinchoq'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('960d89b5-6fbf-479e-adf1-6071dea6c12f', 'slm-sinov-igr-shisha-idishlar', 'Shisha idishlar sinovi', 'Испытание стеклянной посуды', 'Testing of glassware', 'Shisha idishlar sinovi', 'Bolalar o''yinchoqlari xavfsizligi bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'oyinchoqlar'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '913753ac-01c5-4f46-be2e-d00afc531a35', id, 335000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-igr-shisha-idishlar' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-igr-shisha-idishlar'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('f78c2b78-bdf6-4b8c-8234-1fa5ac8169df', 'slm-sinov-igr-velosiped-samokat-kolyaska-yurgich', 'Velosiped, samokat, bolalar kolyaskalari va yurgichlar sinovi', 'Испытание велосипедов, самокатов, детских колясок и ходунков', 'Testing of bicycles, scooters, baby strollers and walkers', 'Velosiped, samokat, bolalar kolyaskalari va yurgichlar sinovi', 'Bolalar o''yinchoqlari xavfsizligi bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'oyinchoqlar'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '953404b6-afd0-469b-aa93-3201ef9ae0cc', id, 335000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-igr-velosiped-samokat-kolyaska-yurgich' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-igr-velosiped-samokat-kolyaska-yurgich'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('bd46c023-00eb-4ea0-affd-2938dfc765d4', 'slm-sinov-igr-velosiped-toliq-sinov', 'Katta va kichik velosipedlar barcha sinovlari', 'Все испытания больших и малых велосипедов', 'Full testing of large and small bicycles', 'Katta va kichik velosipedlar barcha sinovlari', 'Bolalar o''yinchoqlari xavfsizligi bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'oyinchoqlar'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '5b2a325f-05d7-4908-af91-fc6e73deefe3', id, 837500, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-igr-velosiped-toliq-sinov' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-igr-velosiped-toliq-sinov'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('1129425b-0e78-44cd-bd16-92ef7d30a894', 'slm-sinov-igr-oyinchoq-shovqin-darajasi', 'Bolalar o''yinchoqlarini shovqin (shum) darajasini aniqlash', 'Определение уровня шума детских игрушек', 'Determination of noise level of children''s toys', 'Bolalar o''yinchoqlarini shovqin (shum) darajasini aniqlash', 'Bolalar o''yinchoqlari xavfsizligi bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'oyinchoqlar'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '2eccb51b-d8e2-4303-b932-c9611762282d', id, 335000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-igr-oyinchoq-shovqin-darajasi' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-igr-oyinchoq-shovqin-darajasi'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('84ec48ed-bd83-4a14-b111-87569d196160', 'slm-sinov-chir-plastik-profili', 'Plastik profili sinovi', 'Испытание пластиковых профилей', 'Testing of plastic profiles', 'Plastik profili sinovi', 'Mahsulot sifati va xavfsizligi bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'chirchiq'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '0b9a0a21-e57a-43ed-8d98-87395f8a1671', id, 2512500, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-chir-plastik-profili' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-chir-plastik-profili'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('2de9158a-6473-456b-b7fb-d843e078cf68', 'slm-sinov-chir-alyuminiy-profili', 'Alyuminiy profili sinovi', 'Испытание алюминиевых профилей', 'Testing of aluminum profiles', 'Alyuminiy profili sinovi', 'Mahsulot sifati va xavfsizligi bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'chirchiq'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '181b23aa-17f6-4b12-bc13-7328b846c42e', id, 4020000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-chir-alyuminiy-profili' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-chir-alyuminiy-profili'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('6230b3aa-f3c2-4c8e-aba3-bd4ae4720b7a', 'slm-sinov-chir-deraza-eshik-furnitura', 'Deraza va eshiklar uchun furnitura sinovi', 'Испытание фурнитуры для окон и дверей', 'Testing of fittings for windows and doors', 'Deraza va eshiklar uchun furnitura sinovi', 'Mahsulot sifati va xavfsizligi bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'chirchiq'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '45fefa49-332c-4119-a585-a08aba81f1e8', id, 3350000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-chir-deraza-eshik-furnitura' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-chir-deraza-eshik-furnitura'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('69f3c196-f7cf-4852-b928-9dff8e614af5', 'slm-sinov-chir-tish-chotkalari', 'Tish cho''tkalari sinovi', 'Испытание зубных щёток', 'Testing of toothbrushes', 'Tish cho''tkalari sinovi', 'Mahsulot sifati va xavfsizligi bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'chirchiq'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '6fcb31fa-6a50-4a0e-81a5-af14979e4b6d', id, 335000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-chir-tish-chotkalari' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-chir-tish-chotkalari'));

INSERT INTO "Service" ("id", "slug", "nameUz", "nameRu", "nameEn", "testObject", "testType", "laboratoryId", "isActive", "updatedAt") VALUES ('abd4ab14-497c-416d-9df6-7ed55629954e', 'slm-sinov-chir-mineral-ogitlar', 'Mineral o''g''itlar sinovi', 'Испытание минеральных удобрений', 'Testing of mineral fertilizers', 'Mineral o''g''itlar sinovi', 'Mahsulot sifati va xavfsizligi bo''yicha sinov', (SELECT id FROM "Laboratory" WHERE slug = 'chirchiq'), true, CURRENT_TIMESTAMP) ON CONFLICT (slug) DO NOTHING;
INSERT INTO "Price" ("id", "serviceId", "amount", "currency", "isCurrent", "updatedAt") SELECT '704156da-b86e-4997-bbd3-57eae80ababc', id, 402000, 'UZS', true, CURRENT_TIMESTAMP FROM "Service" WHERE slug = 'slm-sinov-chir-mineral-ogitlar' AND NOT EXISTS (SELECT 1 FROM "Price" WHERE "serviceId" = (SELECT id FROM "Service" WHERE slug = 'slm-sinov-chir-mineral-ogitlar'));

